[package]
name = "fieldwise_derive"
version = "0.0.0"
authors = ["Charlie Somerville <charlie@charlie.bz>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
fieldwise = { path = "../fieldwise" }
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
