[package]
name = "mixlab-util"
version = "0.1.0"
authors = ["Charlie Somerville <charlie@charlie.bz>"]
edition = "2018"

[dependencies]
derive_more = "*"
num-rational = { version = "*", features = ["serde"] }
num-traits = "*"
serde = "*"
