[package]
name = "mixlab-codec"
version = "0.0.0"
authors = ["Charlie Somerville <charlie@charlie.bz>"]
edition = "2018"

[dependencies]
bytes = "0.5"
derive_more = "0.99"
futures = "0.3"
lewton = "0.10"
ogg = "0.7"
